server:
  port: 8090

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: wallet-service
          uri: lb://wallet-service
          predicates:
            - Path=/wallet/**
        - id: shop-service
          uri: lb://shop-service
          predicates:
            - Path=/shop/**
        - id: inventory-service
          uri: lb://inventory-service
          predicates:
            - Path=/inventory/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

management:
  endpoint:
    gateway:
      enabled: true           # تأكد من تفعيل endpoint الخاص بالبوابة
  endpoints:
    web:
      exposure:
        include: health,info,gateway
